//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('videos')
export class videosEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  category: string;

  @Column('text', { nullable: true })
  language: string;

  @Column('text', { nullable: true })
  length: string;

  @Column('text', { nullable: true })
  URL: string;
}
