//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { textsEntity } from './db/texts.entity';
import { podcastsEntity } from './db/podcasts.entity';
import { videosEntity } from './db/videos.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      textsEntity,
      podcastsEntity,
      videosEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      texts: [
        { language: 'language 1', id: 67 },
        { language: 'language 2', id: 96 },
        { language: 'language 3', id: 25 },
        { language: 'language 4', id: 100 },
        { language: 'language 5', id: 23 },
      ],
      podcasts: [
        {
          title: 'title 1',
          description: 'description 1',
          language: 'language 1',
          length: 'length 1',
          URL: 'URL 1',
          id: 92,
        },
        {
          title: 'title 2',
          description: 'description 2',
          language: 'language 2',
          length: 'length 2',
          URL: 'URL 2',
          id: 35,
        },
        {
          title: 'title 3',
          description: 'description 3',
          language: 'language 3',
          length: 'length 3',
          URL: 'URL 3',
          id: 45,
        },
        {
          title: 'title 4',
          description: 'description 4',
          language: 'language 4',
          length: 'length 4',
          URL: 'URL 4',
          id: 59,
        },
        {
          title: 'title 5',
          description: 'description 5',
          language: 'language 5',
          length: 'length 5',
          URL: 'URL 5',
          id: 62,
        },
      ],
      videos: [
        {
          title: 'title 1',
          description: 'description 1',
          category: 'category 1',
          language: 'language 1',
          length: 'length 1',
          URL: 'URL 1',
          id: 40,
        },
        {
          title: 'title 2',
          description: 'description 2',
          category: 'category 2',
          language: 'language 2',
          length: 'length 2',
          URL: 'URL 2',
          id: 40,
        },
        {
          title: 'title 3',
          description: 'description 3',
          category: 'category 3',
          language: 'language 3',
          length: 'length 3',
          URL: 'URL 3',
          id: 92,
        },
        {
          title: 'title 4',
          description: 'description 4',
          category: 'category 4',
          language: 'language 4',
          length: 'length 4',
          URL: 'URL 4',
          id: 23,
        },
        {
          title: 'title 5',
          description: 'description 5',
          category: 'category 5',
          language: 'language 5',
          length: 'length 5',
          URL: 'URL 5',
          id: 51,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('textsEntity', data.texts);
      await this.SeedResource('podcastsEntity', data.podcasts);
      await this.SeedResource('videosEntity', data.videos);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
